### ISSUE TITLE
Issue with excluding JSPF

### ISSUE THREAD

**Issue by mattdandrea** [leonardehrenfried/jspc-maven-plugin#17] opened 2017-11-23 15:16 UTC
Hi,

I've tried excluding JSPFs from being part of the compile, but I keep getting errors for them.

I set:
```
<ignoreJspFragmentErrors>true</ignoreJspFragmentErrors>
<includes>**/*.jsp</includes>
<excludes>**/*.jspf</excludes>
```

Anything else you would recommend trying?

Thanks,

Matt

**Comment by leonardehrenfried** [comment] 2017-11-23 15:39
What about 

```xml
<excludes>
  <exclude>**/*.jspf</exclude>
<excludes>
```
I'm totally guessing here, but I was inspired by this: https://maven.apache.org/plugins/maven-jar-plugin/examples/include-exclude.html

**Comment by leonardehrenfried** [comment] 2017-11-23 15:43
Also you can increase the log level and check if your exclusions are picked up correctly, see https://github.com/leonardehrenfried/jspc-maven-plugin/blob/master/src/main/java/io/leonard/maven/plugins/jspc/JspcMojo.java#L389

**Comment by mattdandrea** [comment] 2017-11-23 17:36
Looks like it was included in the logging for exclusions:
`[artifact:mvn] [INFO] Excludes=**/*.jspf`

The syntax:
```
<excludes>
  <exclude>**/*.jspf</exclude>
<excludes>
```
generated an error unfortunately.

**Comment by leonardehrenfried** [comment] 2017-11-23 19:33
This might be a silly question, but you're not referring to a JSPF file from inside a JSP file via an `<include>` or something like that?

**Comment by mattdandrea** [comment] 2017-11-23 20:39
Yes, <%@ include ...> directives are being used.  Is that what is triggering it?  The problem is that some of these JSPFs don't compile successfully on their own - only within the context of the JSPs they are used inside.  You would think maybe ignoreJspFragmentErrors would prevent them from being reported as well.

**Comment by tcollignon** [comment] 2017-11-23 21:05
Hi

Can you share your config and error please? Which version do you use?

In my case this works : 
````
<plugin>
		<groupId>io.leonard.maven.plugins</groupId>
		<artifactId>jspc-maven-plugin</artifactId>
		<version>2.0.0</version>
			<configuration>
				<excludes>
					<exclude>**/*.jspf</exclude>
				</excludes>
				<webAppSourceDirectory>${jspcWebAppSourceDirectory}</webAppSourceDirectory>
				<webXml>${jspcWebXml}</webXml>
				<generatedClasses>${jspGeneratedClasses}</generatedClasses>
				<stopAtFirstError>${jspStopAtFirstError}</stopAtFirstError>
				<threads>${jspThreads}</threads>
			</configuration>

			<dependencies>
				<dependency>
					<groupId>org.apache.tomcat</groupId>
					<artifactId>tomcat-jasper</artifactId>
					<version>8.5.4</version>
					<exclusions>
						<exclusion>
							<groupId>org.eclipse.jdt.core.compiler</groupId>
							<artifactId>ecj</artifactId>
						</exclusion>
					</exclusions>
				</dependency>

				<dependency>
					<groupId>org.eclipse.jdt.core.compiler</groupId>
					<artifactId>ecj</artifactId>
					<version>4.6.1</version>
				</dependency>
			</dependencies>
		</plugin>
````

**Comment by leonardehrenfried** [comment] 2017-11-23 22:07
Okay, I took a look and have written an automated test: https://github.com/leonardehrenfried/jspc-maven-plugin/tree/master/src/test/resources/unit/project_include_exclude

It shows that the includes and excludes work.

@mattdandrea Just a wild guess: Are you maybe putting your JSPs directly in the `webapp` folder? In that case the exclude `**/*.jspf` will not work because it will only exclude JSPFs that are in *sub*folders.

Example:
- `webapp/jsp/1.jspf` will be excluded
- `webapp/1.jspf` willnot be excluded

**Comment by mattdandrea** [comment] 2017-11-24 02:11
No, the JSPFs are in subfolders so that doesn't seem to be it.
In your test, what happens if you use <%@ include ...> to include the JSPF in your 1.jsp? 
Does it get excluded then?
And then, if you could rework the 2.jspf so that it makes use of a variable e.g. the hello variable but doesn't declare it itself.  That is, make it so that it fails compile on its own.  This is the scenario I have.

**Comment by leonardehrenfried** [comment] 2017-11-24 06:59
I suggest you modify the test project to demonstrate the problem you are
having.

This reproduction case will make it much easier for us to diagnose the
problem.

Am 24.11.2017 3:11 vorm. schrieb "mattdandrea" <notifications@github.com>:

**Comment by mattdandrea** [comment] 2017-11-24 20:43
I was able to narrow it down to one JSP that was causing the problem.  When I exclude that one JSP, everything works as expected.  I still am not sure why it happens.  If I figure it out, I will let you know.

**Comment by leonardehrenfried** [comment] 2017-11-25 11:15
Ok, I will close this issue then.

If you can figure out a more precise reproduction case, please reopen it.

**Closed by leonardehrenfried** 2017-11-25 11:15 UTC
